### PR TITLE
Clarify alerts. Fixes issue #40

### PR DESCRIPTION
**Pull request by ekr**
@hannestschofenig @bemasc

### CODE REVIEW

**Comment by hannestschofenig** [comment]
I wonder whether this works. Here is the solution I came up with https://github.com/tlswg/draft-ietf-tls-ctls/pull/47/files

**Comment by ekr** [comment]
yeah that seems more complicated. Is there a reason why this won't work?

**Comment by hannestschofenig** [comment]
IMHO we somehow have to distinguish between three types of message (via the content type): 
- plaintext handshake messages (for the ClientHello, ServerHello/HRR)
- encrypted cTLS messages, and 
- plaintext alert messages

Do I see this wrong?

**Comment by ekr** [comment]
Agreed. But that's


-    plaintext handshake messages (for the ClientHello, ServerHello/HRR)   --> ctls_handshake
-    encrypted cTLS messages, and --> The ordinary DTLS rules
-    plaintext alert messages --> tls alert.

**Comment by hannestschofenig** [comment]
I guess I was thinking about this in a too complicated way. 

Do you want to use the regular TLS Alert message format? (Fine for me.)

**Comment by bemasc** [comment]
I think the logical way to do this would be to register `ctls_handshake` in the [ContentType registry](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-5).  Otherwise, you're setting up a potential collision as more values are added to that registry.

**Comment by bemasc** [comment]
I think the logical way to do this would be to register `ctls_handshake` in the [ContentType registry](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-5).  Otherwise, you're setting up a potential collision as more values are added to that registry.

**Comment by ekr** [comment]
Yes, I agree with that. I'm just talking about the technical approach

**Comment by bemasc** [comment]
OK, then I think this PR might as well add the IANA instruction for that.

**Comment by ekr** [comment]
I made a separate IANA PR
https://github.com/tlswg/draft-ietf-tls-ctls/pull/53

**Pull request merged**
